### ISSUE TITLE
bug_闪退

### ISSUE THREAD

**Issue by yhzhan1002** [SusionSuc/Boring#3]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.susion.boring, PID: 15965
                  java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
                      at java.lang.Thread.nativeCreate(Native Method)
                      at java.lang.Thread.start(Thread.java:1063)
                      at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
                      at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1553)
                      at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:306)
                      at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:503)
                      at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:602)
                      at rx.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:240)
                      at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker.schedule(CachedThreadScheduler.java:214)
                      at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker.schedule(CachedThreadScheduler.java:204)
                      at rx.internal.operators.OperatorSubscribeOn.call(OperatorSubscribeOn.java:45)
                      at rx.internal.operators.OperatorSubscribeOn.call(OperatorSubscribeOn.java:30)
                      at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                      at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                      at rx.Observable.subscribe(Observable.java:8759)
                      at rx.Observable.subscribe(Observable.java:8726)
                      at rx.Observable.subscribe(Observable.java:8640)
                      at com.susion.boring.utils.AlbumUtils.setAlbum(AlbumUtils.java:50)
                      at com.susion.boring.music.itemhandler.LocalMusicIH.bindData(LocalMusicIH.java:57)
                      at com.susion.boring.music.itemhandler.LocalMusicIH.bindData(LocalMusicIH.java:21)
                      at com.susion.boring.music.itemhandler.SimpleMusicIH.onBindDataView(SimpleMusicIH.java:49)
                      at com.susion.boring.base.ui.SimpleItemHandler.onBindView(SimpleItemHandler.java:39)
                      at com.susion.boring.base.adapter.BaseRVAdapter.onBindViewHolder(BaseRVAdapter.java:96)
                      at com.susion.boring.base.view.LoadMoreRecycleView$LoadMoreAdapter.onBindViewHolder(LoadMoreRecycleView.java:104)
                      at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5825)
                      at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5858)
                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5094)
                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4970)
                      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                      at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1193)
                      at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1043)
                      at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4413)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:590)
                      at android.view.Choreographer.doFrame(Choreographer.java:559)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:145)
                      at android.app.ActivityThread.main(ActivityThread.java:6117)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by yhzhan1002** [comment]
扫描本地音频后，手动上下拉出现的音频列表，突然闪退

**Comment by yhzhan1002** [comment]
出现的音频列表里面
